# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout  # the code
      - add_ssh_keys:
          fingerprints: ["9a:70:2b:7c:55:36:ab:26:8a:0f:94:c7:d3:b8:06:4d"]
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for my playbook
            apk add --update ansible
      - run: # Install ansible in the agent that is running this job
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  my-workflow:
    jobs:
      - configure_infrastructure
